### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = './srgan_weights_epoch_240.h5', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by mustaeenqazi** [AvivSham/SRGAN-Keras-Implementation#3]
Hi Aviv, Thanks for the good code, i run into this error using your notebook, while running the training cell. somehow the load_weights function cannot open the folder

**Comment by AvivSham** [comment]
I didn't provide the weights of the model. Please change the path of the model weights to the path where you save your weights while training, this should solve your problem.
