### ISSUE TITLE
incompatible layer problem when creating the model

### ISSUE THREAD

**Issue by Teragron** [AvivSham/SRGAN-Keras-Implementation#4]
I'm trying to create a model with
`model_srgan = SRGAN()` in my jupyter Notebook.
However as a run the code it gives me a ValueError " Input 0 of layer fc1 is incompatible with the layer: expected axis -1 of input shape to have value 25088 but received input with shape [None, 32768]
"
Right now i'm using a very small custom dataset, but this also occured when i was trying with DIV2K dataset.

(tensorflow version: 2.3.0)

`WARNING:tensorflow:Model was constructed with shape (None, 224, 224, 3) for input Tensor("input_3:0", shape=(None, 224, 224, 3), dtype=float32), but it was called on an input with incompatible shape (None, 256, 256, 3).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-1b41366ffd02> in <module>
----> 1 model_srgan = SRGAN()

<ipython-input-15-53becdbc8b38> in __init__(self, lr_height, lr_width, channels, upscale_factor, generator_lr, discriminator_lr, gan_lr)
     24         opti_gan = Adam(gan_lr,0.9)
     25 
---> 26         self.vgg = self.bulid_vgg()
     27 
     28         self.discriminator = self.build_discriminator(opti_discriminator)

<ipython-input-15-53becdbc8b38> in bulid_vgg(self)
     79         vgg.outputs = [vgg.layers[9].output]
     80         img = Input(shape = self.shape_high_reso)
---> 81         img_features = vgg(img)
     82         vgg_model = Model(img, img_features)
     83 #         for layer in vgg_model.layers:

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1115           try:
   1116             with ops.enable_auto_cast_variables(self._compute_dtype_object):
-> 1117               outputs = call_fn(cast_inputs, *args, **kwargs)
   1118 
   1119           except errors.OperatorNotAllowedInGraphError as e:

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\functional.py in call(self, inputs, training, mask)
    384     """
    385     return self._run_internal_graph(
--> 386         inputs, training=training, mask=mask)
    387 
    388   def compute_output_shape(self, input_shape):

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\functional.py in _run_internal_graph(self, inputs, training, mask)
    506 
    507         args, kwargs = node.map_arguments(tensor_dict)
--> 508         outputs = node.layer(*args, **kwargs)
    509 
    510         # Update tensor_dict.

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1090       # TODO(reedwm): We should assert input compatibility after the inputs
   1091       # are casted, not before.
-> 1092       input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
   1093       graph = backend.get_graph()
   1094       # Use `self._name_scope()` to avoid auto-incrementing the name.

~\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\keras\engine\input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    214                 ' incompatible with the layer: expected axis ' + str(axis) +
    215                 ' of input shape to have value ' + str(value) +
--> 216                 ' but received input with shape ' + str(shape))
    217     # Check shape.
    218     if spec.shape is not None:

ValueError: Input 0 of layer fc1 is incompatible with the layer: expected axis -1 of input shape to have value 25088 but received input with shape [None, 32768]
`

**Comment by AvivSham** [comment]
you need to change the initialization of the model when calling:
`model_srgan = SRGAN()` you need to pass the low res height and width along with the upsampling ratio.
This should sort your problem.

**Comment by AvivSham** [comment]
If you still facing this issue please reopen it.

**Comment by manmeet3591** [comment]
> you need to change the initialization of the model when calling:
> `model_srgan = SRGAN()` you need to pass the low res height and width along with the upsampling ratio.
> This should sort your problem.

Specifically, this one worked for me:
SRGAN(lr_height = 56,lr_width = 56,upscale_factor = 4 )

Commenting here just to help anyone who gets stuck in future.

**Comment by AvivSham** [comment]
> you need to change the initialization of the model when calling:
> `model_srgan = SRGAN()` you need to pass the low res height and width along with the upsampling ratio.
> This should sort your problem.

This is exactly what I wrote in this comment. You can play with the low-resolution dimensions in addition to the upscale factor :)
