### ISSUE TITLE
getting IndexError: pop from empty list error while creating the SRGAN model

### ISSUE THREAD

**Issue by heervit2020** [AvivSham/SRGAN-Keras-Implementation#5]
getting error while executing this code-> model_srgan = SRGAN(lr_height=56, lr_width=56, channels=3, upscale_factor=4)
dataset i am using is Blur QR code dataset
![error](https://user-images.githubusercontent.com/76156500/118392743-bda4bf00-b658-11eb-8ff5-90fd5d101637.jpg)

**Comment by sadekujjaman** [comment]
@heervit2020 how can you solve this problem?

**Comment by AvivSham** [comment]
did you give a correct path for the dataset?
@sadekujjaman does your problem solved?

**Comment by sadekujjaman** [comment]
@AvivSham 
It doesn't seem to be a problem for the dataset.
SRGAN's init function gives an error when the call is made (vgg model is built). I gave the input correctly. 

This happened while building the vgg model. This error is coming in the following line of code.
`img_features = vgg(img)`
![vgg_1](https://user-images.githubusercontent.com/34203645/121801579-d73a2600-cc59-11eb-8fff-89cc941076fa.PNG)
![vgg_2](https://user-images.githubusercontent.com/34203645/121801583-dacdad00-cc59-11eb-809b-28c5ebc525dc.PNG)
![vgg_3](https://user-images.githubusercontent.com/34203645/121801587-df926100-cc59-11eb-8e5b-34a369a5b188.PNG)

**Comment by sadekujjaman** [comment]
@AvivSham would you please check this problem?

**Comment by AvivSham** [comment]
@sadekujjaman I just run the the notebook and it works for me.

**Comment by sadekujjaman** [comment]
Here is my implementation, I'm still getting this error.
[My Implementation](https://github.com/sadekujjaman/Machine-Learning/blob/main/SIMPLE_SRGAN.ipynb)

**Comment by AvivSham** [comment]
Hi @sadekujjaman with all the respect I won't go through your code I'm a full time researcher and I have other stuff to do as well. Try to fight with it a bit, I run it with `from tensorflow.keras.applications import VGG19` try to do the same or you can manually downgrade Keras and try once again.
The error you show here relates to the dependencies and not my written code.

**Comment by sadekujjaman** [comment]
@AvivSham Would you please mention your tensorflow and keras version?

**Comment by sadekujjaman** [comment]
@AvivSham problem solved. Thanks.
I used from `keras.applications.vgg19 import VGG19` instead of `tensorflow.keras.applications import VGG19`.

`tensorflow.keras.applications import VGG19` solved the problem.

@AvivSham  You should update your notebook with `tensorflow.keras.applications import VGG19`.
