### ISSUE TITLE
error warning

### ISSUE THREAD

**Issue by maryamserdar** [AvivSham/SRGAN-Keras-Implementation#6]
i am trying to run the code but this error keep occurring.
what is the solution for it.
thanks in advanced

model_srgan = SRGAN(high_reso_imgs,low_reso_imgs)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-86fd81ebe204> in <module>()
----> 1 model_srgan = SRGAN(high_reso_imgs,low_reso_imgs)

<ipython-input-24-624304c19a52> in __init__(self, high_reso_imgs, low_reso_imgs, lr_height, lr_width, channels, upscale_factor, generator_lr, discriminator_lr, gan_lr)
     20         self.shape_high_reso = (self.height_high_reso, self.width_high_reso, self.channels)
     21 
---> 22         self.samples = high_reso_imgs.shape
     23 
     24         opti_generator = Adam(generator_lr, 0.9)

AttributeError: 'list' object has no attribute 'shape'

**Comment by AvivSham** [comment]
the images you pass to `model_srgan` should be numpy array, can you please check if that is the case?

**Comment by sadekujjaman** [comment]
@maryamserdar Just try the following lines of code(Update with it). It will solve the problem.

`high_reso_imgs = np.array(img_list)`
`low_reso_imgs = np.array(img_low_list)`
![np_1](https://user-images.githubusercontent.com/34203645/121800807-b7a0fe80-cc55-11eb-8dd5-f99a677f6003.PNG)

**Comment by AvivSham** [comment]
can you please print `os.listdir()`?

**Comment by maryamserdar** [comment]
thanks for replying
i used these lines and the error is solved
but  I am facing another issue with the code related to vgg19
thanks for your help
best regards

**Comment by maryamserdar** [comment]
thanks for replying
i used these lines high_reso_imgs = np.array(img_list)
low_reso_imgs = np.array(img_low_list)
and the error is solved
but  I am facing another issue with the code related to vgg19
thanks for your help
best regards

**Comment by sadekujjaman** [comment]
@maryamserdar What kind of issue are you facing related to vgg19?

**Comment by maryamserdar** [comment]
the following warning :  WARNING:tensorflow:Model was constructed with
shape (None, 224, 224, 3) for input
KerasTensor(type_spec=TensorSpec(shape=(None, 224, 224, 3),
dtype=tf.float32, name='input_3'), name='input_3', description="created by
layer 'input_3'"), but it was called on an input with incompatible shape
(None, 256, 256, 3)

ValueError: Input 0 of layer fc1 is incompatible with the layer: expected
axis -1 of input shape to have value 25088 but received input with shape
(None, 32768)

**Comment by sadekujjaman** [comment]
@maryamserdar  
Try this line for model constructor. Hope it will save your day.
`model_srgan = SRGAN(lr_height=56, lr_width=56, channels=3, upscale_factor=4)`

**Comment by maryamserdar** [comment]
unfortunately, now it gives  pop from empty list

**Comment by sadekujjaman** [comment]
@maryamserdar 
Use `tensorflow.keras.applications import VGG19` instead `from keras.applications.vgg19 import VGG19`.

`tensorflow.keras.applications import VGG19` solved this problem.
