### ISSUE TITLE
pop from empty list

### ISSUE THREAD

**Issue by sadekujjaman** [AvivSham/SRGAN-Keras-Implementation#7]
When I run the notebook, I get the following error.
**IndexError: pop from empty list**
This happened while building the vgg model. This error is coming in the following line of code. 
`img_features = vgg(img)`
![vgg_1](https://user-images.githubusercontent.com/34203645/121800655-026e4680-cc55-11eb-9cf0-335e5c3376ff.PNG)
![vgg_2](https://user-images.githubusercontent.com/34203645/121800662-07cb9100-cc55-11eb-86eb-0a67657c05e3.PNG)
![vgg_3](https://user-images.githubusercontent.com/34203645/121800664-0b5f1800-cc55-11eb-9a22-713141031d45.PNG)

**Comment by maryamserdar** [comment]
i am having the exact same problem. what is the solution please .

**Comment by AvivSham** [comment]
When did you cloned the repo? I recently pushed some changes aim to solve this issue.

**Comment by sadekujjaman** [comment]
@maryamserdar 
Latest update  made by @AvivSham solve this problem. 
Or you have to update your notebook with following two changes.
1. use `tensorflow.keras.applications import VGG19` instead of  `keras.applications.vgg19 import VGG19` in import level.
2. call SRGAN with following argument `model_srgan = SRGAN(lr_height=56, lr_width=56, channels=3, upscale_factor=4)`
