### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by subinga18** [AvivSham/SRGAN-Keras-Implementation#8]
<img width="634" alt="스크린샷 2021-12-01 오후 12 21 33" src="https://user-images.githubusercontent.com/38221941/144166176-d7a031ce-c2f4-4f2d-916e-5fc2e9cb3eea.png">
how can I fix those errors?

**Comment by AvivSham** [comment]
as far as I can tell `high_reso_imgs` should be np array instead of list.

**Comment by AvivSham** [comment]
If you still won't able to solve this problem please drop here your email and I will reach out so you can send me your notebook.

**Comment by subinga18** [comment]
you mean, high_reso_imgs = np.array(img_list)?
I tried this one but another error came out.
email address : subinga18@naver.com 
thank you for helping me.

**Comment by srujanayadav** [comment]
> If you still won't able to solve this problem please drop here your email and I will reach out so you can send me your notebooseethasrujana2002@gmail.com

**Comment by srujanayadav** [comment]
> If you still won't able to solve this problem please drop here your email and I will reach out so you can send me your notebook.

mailid:  srujanayadav28@gmail.com

**Comment by srujanayadav** [comment]
Please fix this error send the exact code
