### ISSUE TITLE
SRGAN beginner

### ISSUE THREAD

**Issue by eshwarkamal** [AvivSham/SRGAN-Keras-Implementation#9]
Hi Avivsham,
It's really cool to see your SRGAN work. Could you share the GPU series requirements and its configurations to achieve the final model like you?
It would be a huge help for beginners, including me.

**Comment by AvivSham** [comment]
What do you mean requirements, can you be more specific?

**Comment by eshwarkamal** [comment]
> What do you mean requirements, can you be more specific?

Yup, I have the 8GB RAM and 4GB-RTX3050 GPU card. 
is it sufficient to train the model with this "!wget http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip"-dataset ?

@AvivSham bro, kindly reply the issue asap, it will more helpful for us

**Comment by DaitiDay** [comment]
I'm also interested in the GPU requirements for such a training

**Comment by AvivSham** [comment]
I don't have the answer for this question since I didn't benchmark different GPUs. Please try to train the model with BS 1/2 and see if your GPU memory is sufficient for such training. If not you will probably be able to run it on google colab, but for limited #epochs since it is limited in time.
